package com.webappypie.optilens.core.imaging.fusion

import com.webappypie.optilens.core.camera.burst.model.FrameMetadata

/**
 * Final high-quality computational photography product generated by [MultiFrameFusionEngine].
 *
 * @param jpegBytes Final compressed JPEG image bytes.
 * @param yuvBytes Optional uncompressed processed YUV420 buffer (useful for diagnostics/contact sheets).
 * @param width Pixel width.
 * @param height Pixel height.
 * @param colorProfile Applied color grading profile.
 * @param diagnostics Execution latency and quality metrics.
 * @param metadata Combined/anchor optical metadata.
 */
data class FusedPhoto(
    val jpegBytes: ByteArray,
    val yuvBytes: ByteArray? = null,
    val width: Int,
    val height: Int,
    val colorProfile: ColorProfile,
    val diagnostics: FusionDiagnostics,
    val metadata: FrameMetadata,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is FusedPhoto) return false
        return width == other.width &&
            height == other.height &&
            colorProfile == other.colorProfile &&
            diagnostics == other.diagnostics &&
            metadata == other.metadata &&
            jpegBytes.contentEquals(other.jpegBytes)
    }

    override fun hashCode(): Int {
        var result = width
        result = 31 * result + height
        result = 31 * result + colorProfile.hashCode()
        result = 31 * result + diagnostics.hashCode()
        result = 31 * result + metadata.hashCode()
        result = 31 * result + jpegBytes.contentHashCode()
        return result
    }
}
